gText_Birch_Welcome:: @ 82C897B
	.string "¡Hola! ¡Yo soy el PROFESOR BIRCH!\n"
	.string "¡Soy un Profesor POKéMON!\p"
	.string "$"
gText_Birch_Pokemon:: @ 82C89FB
    .string "Los Monstruos de Bolsillo, 'Pocket\n"
    .string "Monsters', o para abreviar, POKéMON,\l"
    .string "invaden nuestro mundo.\p"
    .string "Y este, es mi 'POKéMON' favorito.\p"
	.string "\n"
	.string "$"
gText_Birch_MainSpeech:: @ 82C8A1F
	.string "El mundo está lleno de POKéMON.\p"
	.string "Yo los estudio como profesión, y\n"
	.string "paso mucho tiempo en el campo por eso.\p"
    .string "¡Hay tantos misterios impresionantes\n"
    .string "que los envuelven! ¡Me apasionan!\p"
	.string "Estás por iniciar una aventura\n"
	.string "sin precedentes...\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Entonces...\n"
	.string "¿Y tú cómo jugarás?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "¿Serás el chico?\n"
	.string "¿O la chica?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "¿Cómo te gustaría\n"
	.string "que te llamen?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Oh, entonces\n"
	.string "¿Serás {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "¡Perfecto!\p"
	.string "Eres {PLAYER}{KUN}, que te mudaste\n"
	.string "desde JOHTO hasta LITTLEROOT.\l"
	.string "¡Prepárate!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "¡Una nueva aventura está por iniciar!\p"
	.string "¡Tendrás POKéMON, librarás COMBATES y\n"
	.string "vivirás una historia renovada!\p"
	.string "Te estaré esperando, quizá esté\n"
	.string "en el LABORATORIO o quizá no...\p"
	.string "$"
