gText_ObtainedTheItem:: @ 8272A78
	.string "¡Has obtenido {STR_VAR_2}!$"
	
gText_ObtainedTheItems::
    .string "¡Obtuviste {STR_VAR_1} {STR_VAR_2}!$"
	
gText_TheBagIsFull:: @ 8272A89
	.string "La mochila está llena…$"

gText_PutItemInPocket:: @ 8272A9A
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el bolsillo {STR_VAR_3}.$"

gText_PlayerFoundOneItem:: @ 8272ABF
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull:: @ 8272AD0
	.string "¡Mala suerte!\n"
	.string "La mochila está llena…$"

gText_PlayerPutItemInBag:: @ 8272AEA
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en la Mochila.$"

gText_ObtainedTheDecor:: @ 8272B09
	.string "¡Has obtenido {STR_VAR_2}!$"

gText_NoRoomLeftForAnother:: @ 8272B1A
	.string "¡Mala suerte! No queda lugar\n"
	.string "par más {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC:: @ 8272B48
	.string "{STR_VAR_2} se ha transferido\n"
	.string "a tu PC.$"
